Ex14
kitkazak/external-courses pull request #15
Opened 2019-04-29 14:56 UTC by kitkazak

# Практическая работа 14 - Контекст в JavaScript.

## Задание 1

Создать калькулятор с аналогичным практической работе "Функции в JavaScript" API со следующими доработками:

-   выполнять арифметические операции также можно следующим образом:

    ```js
    const result = Calculator.add(100)
        .multiply(2)
        .divide(20)
        .reset()
        .subtract(1)
        .getResult();

    console.log(result); // -1
    ```

-   у калькулятора должен быть метод для установки текущего состояния калькулятора

    ```js
    console.log(Calculator.getResult()); // 0

    Calculator.setState(1);

    console.log(Calculator.getResult()); // 1
    ```

-   у калькулятора должен быть метод, эмулирующий запрос к серверу и устанавливающий состояние калькулятора, равное **500**, при получении ответа с помощью переданного коллбека.

    ```js
    console.log(Calculator.getResult()); // 0

    Calculator.fetchData(/** callback */);

    // -- завершение асинхронной операции --

    console.log(Calculator.getResult()); // 500
    ```

## Задание 2

Создать игру виселица. Виселица — простая игра, в которой загадывается слово, а игрок пытается его угадать, называя по одной букве за раз. Если игрок назвал неправильную букву, то ему начисляется одна ошибка. Если буква была названа правильно, то эта буква показывается в слове. Игра продолжается до тех пор, пока игрок не угадает слово или не совершит **6** ошибок.

Создайте функцию конструктор `Hangman`, которая принимает один аргумент - слово, которое необходимо отгадать. Регистр букв не учитывается.  

```javascript
var hangman = new Hangman('webpurple');
```

Реализуйте метод `guess`, который принимает букву, которую игрок пытается угадать. Если игрок угадал, то необходимо вывести строку с угаданными буквами, неизвестные буквы должны быть заменены символами `_`. Если игрок не угадал, то необходимо вывести количество оставшихся ошибок и введённые им неправильные буквы через разделитель `|`.

```javascript
hangman.guess('w'); // "w________"
hangman.guess('e'); // "we______e"
hangman.guess('a'); // "wrong letter, errors left 5 | a"
hangman.guess('p'); // "we_p__p_e"
hangman.guess('k'); // "wrong letter, errors left 4 | a,k"
```

Реализуйте метод `getGuessedString`, который возвращает строку с угаданными буквами:

```javascript
hangman.getGuessedString(); // we_p__p_e
```

Реализуйте метод `getErrorsLeft`, который возвращает количество оставшихся ошибок:

```javascript
hangman.getErrorsLeft(); // 4
```

Реализуйте метод `getWrongSymbols`, который возвращает массив с неправильно угаданными символами:

```javascript
hangman.getWrongSymbols(); // ["a","k"]
```

Реализуйте метод `getStatus`, который возвращает строку с угаданными буквами и количество оставшихся ошибок:

```javascript
hangman.getStatus(); // "we_p__p_e | errors left 4"
```

Пользователь должен иметь возможность производить подобные действия:

```javascript
hangman.guess('b') // "webp___p_e"
  .guess('l') // "webp__ple"
  .guess('u') // "webpu_ple"
  .guess('r'); // "webpurple | You won!"
```

Реализуйте метод `startAgain`, который принимает в качестве аргумента новое слово и сбрасывает все значения свойств к исходным.

```javascript
hangman.startAgain('webpurple')
  .guess('w') // "w________"
  .getStatus(); // "w_______ | errors left 6"
```

2019-04-29 19:07 UTC, eugrdn requested changes

2019-04-29 19:07 UTC, eugrdn commented on src/ex14_js-context/task-01.js
> +        if (num !== undefined) {
лучше сделать проверку на число, и давай вынесем в ее отдельный метод/функцию

2019-04-29 19:07 UTC, eugrdn commented on src/ex14_js-context/task-01.js
> +        if ( !isNaN(callback(500)) ) {
функция должна быть асинхронной (можешь использовать setTimeout), самому устанавливать state = 500 не нужно, это делает колбек

2019-04-29 19:07 UTC, eugrdn commented on src/ex14_js-context/task-02.js
> +        errors = 6,
лучше назвать errorsLeft или lifes, поскольку это начало игры и пользователь только начинает играть

2019-04-29 19:07 UTC, eugrdn commented on src/ex14_js-context/task-02.js
> +        wrongSymbols = [];
2-4 тоже самое происходит в методе startAgain, давай вынесем в отдельный метод прим. initGame

2019-04-30 23:12 UTC, kitkazak commented on src/ex14_js-context/task-01.js
> +        if (num !== undefined) {
Вынести функцию в глобальную область видимости? Просто здесь объект, не созданный через конструктор, поэтому по-другому не получится.

2019-05-01 11:02 UTC, eugrdn commented on src/ex14_js-context/task-01.js
> +        if (num !== undefined) {
можно сделать метод приватный (с __названием), либо в глобальную область, да, либо использовать паттерн модуль вместо простого объекта

2019-05-01 17:00 UTC, merged