Library
kitkazak/external-courses pull request #16
Opened 2019-05-04 10:45 UTC by kitkazak

Попробовал сделать запрос через xhr, чтобы книги подгружались при загрузке страницы.

2019-05-05 09:31 UTC, eugrdn commented
скролл должен быть внутри секции с книгами `books` и историей `sidebar__history sidebar__panel`, + сайдбар не не должен вылезать за футер

можешь в этой же ветке делать интерактивный рейтинг

2019-05-05 09:31 UTC, eugrdn requested changes

2019-05-05 09:31 UTC, eugrdn commented on src/library/scripts/booksRequest.js
> +function booksRequest() {
подождем до лекции по ajax

2019-05-05 14:46 UTC, kitkazak commented
Исправил верстку, теперь скроллы в `books` и `sidebar__history`, но появились проблемы с билдом.
Travis пишет: 

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> The build has been terminated

Package.json не трогал, делал изменения только в .css и index.html.

2019-05-05 15:42 UTC, eugrdn commented
попробуй перезапустить в тревисе

2019-05-05 15:48 UTC, kitkazak commented
> 
> 
> попробуй перезапустить в тревисе

Получилось ٩(｡•́‿•̀｡)۶

2019-05-05 15:56 UTC, eugrdn commented
пока не мержу ветку, жду звезды, так?

2019-05-05 16:00 UTC, kitkazak commented
Да

2019-05-05 16:22 UTC, eugrdn commented
в кратце: отлавливаешь событие на контейнере со звездами, находишь по id текущую книгу, изменяешь ее поле rating, перерендериваешь

2019-05-05 17:28 UTC, kitkazak commented
> 
> 
> вкратце: отлавливаешь событие на контейнере со звездами, находишь по id текущую книгу, изменяешь ее поле rating, перерендериваешь

Сделал. Создал класс `Book`, в котором повесил обработчик на контейнер со звездами для соответствующей книги.

2019-05-05 17:44 UTC, eugrdn commented
> Сделал.
Здорово, было бы неплохо еще сбрасывать рейтинг если нажимаешь на уже заполненную звезду
> Создал класс Book, в котором повесил обработчик на контейнер со звездами для соответствующей книги.

пока оставь ладно, потом немного переделаем

2019-05-10 10:10 UTC, eugrdn commented
что-то теперь устанавливается некорректно

2019-05-10 16:54 UTC, kitkazak commented
Добавил возможность сбрасывать звезды при нажатии на заполненную звезду и появление заметки о изменении рейтинга в истории.

> 
> 
> что-то теперь устанавливается некорректно

Hover на звездах работает в фаерфоксе, в хроме же конфликт onmouseover и onmouseclick, не понимаю как его решить.

2019-05-12 09:32 UTC, eugrdn commented
там дело не в хроме, а в том, что у тебя постоянно вызывается onmouseover, даже без изменения позиации мыши, так не долджно быть

2019-05-27 20:52 UTC, eugrdn requested changes

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/model/model.js
> +        var __filteredBooksArr = this.filterBooks();
лушче `getFilterBooks`

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/model/model.js
> +                return word.toLowerCase();
а почему бы сначала не объединить в список все слова, а потом все привести к lowerCase

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/model/model.js
> +            bookTitleWords.forEach(word => {
.concat

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/model/model.js
> +            for (let i = 0; i < checkWords.length; i++) {
используй .find

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/index.js
> +        then(res => res.json()).
это лучше вынести в саму функцию утилиту

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/index.js
> +        then(res => res.json()).
точки ставятся с новой строки

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/index.js
> +            model.loadedBooksArr = response;
используй метод для этого и response здесь и так понятно, что это книги -- books

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/model/model.js
> +        for (let i = 0; i < this.loadedBooksArr.length; i++) {
.find

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/view/view.js
> +        for (let i = 0; i < books.length; i++) {
.forEach?

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/view/view.js
> +        ratingContainer = document.createElement('ul');
`var`

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/view/view.js
> +        note.innerHTML =
может это сделать последним вариантом в else ниже?

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/view/view.js
> +        if (noteDetails.event === 'filter') {
сделай форматирование во всех файлах

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/view/view.js
> +        setInterval(function() {
у тебя каждый рендер будет добавлять новый интервал, который ты потом не очищаешь, не хорого

2019-05-27 20:52 UTC, eugrdn commented on src/library/src/view/view.js
> +    View.prototype.__msToTime = function(s) {
это в утилиты

2019-05-29 19:18 UTC, eugrdn requested changes

2019-05-29 19:18 UTC, eugrdn commented on src/library/src/controller/controller.js
> +(function(){
use strict?

2019-05-29 19:18 UTC, eugrdn commented on src/library/src/utils/initialRequest.js
> +function initialRequest(controller, view) {
неправильно
эта функция делает запрос. любой. у нее нет контекста view, controller, model, она не знает про книги

2019-05-29 19:18 UTC, eugrdn commented on src/library/src/model/model.js
> +            .concat(book.title.split(' '))
почему бы не добавить ее в первый массив?

2019-05-30 16:26 UTC, kitkazak commented on src/library/src/utils/initialRequest.js
> +function initialRequest(controller, view) {
Я не могу понять, как правильно реализовать функцию, которая выполняет асинхронный запрос, и затем отрендерить книги, когда она отработает

2019-05-30 16:40 UTC, kitkazak commented on src/library/src/utils/initialRequest.js
> +function initialRequest(controller, view) {
Можно попробовать через async/await?

2019-06-02 14:22 UTC, kitkazak commented
Сделал добавление книги и отформатировал файлы. Если будет время, постараюсь исправить ошибки. Точно не успею сделать ховер на звездах.

Выполнил интерактивный рейтинг и фильтры (вместе), поиск, историю, добавление новой книги, debounce, загрузку книг, mvc.

@eugrdn

2019-06-03 07:50 UTC, eugrdn commented on src/library/src/model/model.js
> +          if (book.rating === 5) return true;
`return book.rating === 5`

2019-06-03 07:50 UTC, eugrdn commented on src/library/src/model/model.js
> +      return false;
это никогда не выполнится

2022-04-18 16:58 UTC, closed without merging